export { RemotePanel, RemotePeerCard } from "./remote.jsx"
export { GeneralPanel } from "./general.jsx"
export { SearchPanel } from "./search.jsx"
export { EmbeddingSettingsSection, ModelsPanel } from "./models.jsx"
export { ChannelsPanel } from "./channels.jsx"
export { AgentsPanel } from "./agents.jsx"
export { AppearancePanel, CustomToolsPanel } from "./appearance.jsx"
export { CapabilitiesPanel } from "./capabilities.jsx"
export { DataPanel, requestDataPanelStorage } from "./data.jsx"
export { AboutPanel } from "./about.jsx"
export { ExtensionsPanel } from "./extensions.jsx"
export { CustomPluginsPanel } from "./custom-plugins.jsx"
export { ShortcutsPanel } from "./shortcuts.jsx"
export { BudgetPanel } from "./budget.jsx"
