export { RemotePanel, RemotePeerCard } from "./remote.jsx"
export { GeneralPanel } from "./general.jsx"
export { SearchPanel } from "./search.jsx"
export { ChannelsPanel } from "./channels.jsx"
export { AgentsPanel } from "./agents.jsx"
export { AppearancePanel } from "./appearance.jsx"
export { CapabilitiesPanel } from "./capabilities.jsx"
export { DataPanel, requestDataPanelStorage } from "./data.jsx"
export { AboutPanel } from "./about.jsx"
export { PluginRegistryPanel } from "./custom-plugins.jsx"
export { ShortcutsPanel } from "./shortcuts.jsx"
export { BudgetPanel } from "./budget.jsx"
export { MediaPanel } from "./media.jsx"
